[package]
name = "omastore-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
development-catalogue = ["omastore-workflow/development-workflow"]

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
omastore-catalogue.workspace = true
chrono.workspace = true
ureq = { version = "3.4", default-features = false, features = ["rustls", "gzip", "json"] }
tempfile = "3.23"
omastore-workflow.workspace = true
url.workspace = true
base64.workspace = true
sha2.workspace = true
rusqlite.workspace = true
libc = "0.2"
